name: desafio_vesti
description: Desafio técnico proposto pela empresa Vesti

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
